# The URL the site will be built for
base_url = "https://example.com"

title = "Okno's blog"

description = """
Hello, I am Paul Delafosse AKA Okno, Java software developper by day 
Rustacean by night. 
"""

compile_sass = true

highlight_code = true

build_search_index = true

theme = "hyde"

[extra]
hyde_theme = "theme-base-0d"
hyde_sticky = true
hyde_reverse = false
hyde_links = []

[author]
name = "Paul Delafosse"
homepage = "https://www.vincentprouillet.com"
